name: hydemanager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

license: GPL-3.0
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  bitsdojo_window: ^0.1.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  system_info2: ^4.0.0
  tray_manager: ^0.5.0
  url_launcher: ^6.3.1
  window_manager: ^0.5.0
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  toastification: ^3.0.3
  connectivity_plus: ^6.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  intl_utils: ^2.8.10
  build_runner: ^2.5.4



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
